import type { Product } from "@/types";

export const productsMock: Product[] = [
  {
    id: "1",
    title: "Qo'l soat qizlar uchun",
    description: "Zamonaviy dizayndagi kvadrat soat",
    imageUrl: "https://picsum.photos/200?random=1",
    price: 120,
    stock: 15,
  },
  {
    id: "2",
    title: "Sport krossovka",
    description: "Yengil va qulay yugurish uchun krossovka",
    imageUrl: "https://picsum.photos/200?random=2",
    price: 250,
    stock: 8,
  },
  {
    id: "3",
    title: "Bluetooth quloqchin",
    description: "Simsiz, yuqori sifatli ovoz",
    imageUrl: "https://picsum.photos/200?random=3",
    price: 180,
    stock: 20,
  },
  {
    id: "4",
    title: "Erkaklar uchun sumka",
    description: "Charm materialdan tayyorlangan sumka",
    imageUrl: "https://picsum.photos/200?random=4",
    price: 300,
    stock: 5,
  },
  {
    id: "5",
    title: "Qizlar uchun ryukzak",
    description: "Rang-barang va qulay ryukzak",
    imageUrl: "https://picsum.photos/200?random=5",
    price: 140,
    stock: 12,
  },
  {
    id: "6",
    title: "Smart soat",
    description: "Fitness tracking va bildirishnomalar bilan",
    imageUrl: "https://picsum.photos/200?random=6",
    price: 500,
    stock: 7,
  },
  {
    id: "7",
    title: "Telefon uchun holder",
    description: "Mashina ichida telefon ushlagich",
    imageUrl: "https://picsum.photos/200?random=7",
    price: 60,
    stock: 25,
  },
  {
    id: "8",
    title: "USB fleshka 64GB",
    description: "Tezkor va ishonchli xotira qurilmasi",
    imageUrl: "https://picsum.photos/200?random=8",
    price: 90,
    stock: 30,
  },
  {
    id: "9",
    title: "Laptop uchun sovutgich",
    description: "Ventilyatorli sovutish paneli",
    imageUrl: "https://picsum.photos/200?random=9",
    price: 220,
    stock: 10,
  },
  {
    id: "10",
    title: "Mini kolonka",
    description: "Portativ bluetooth speaker",
    imageUrl: "https://picsum.photos/200?random=10",
    price: 160,
    stock: 18,
  },
];
