export const ENDPOINTS = {
  REFRESH: "/api/auth/refresh",
  LOGIN: "/api/auth/login",
  ME: "/api/auth/me",
  LOGOUT: "/api/auth/logout",
  TENANTS: "/api/tenants",
  TEACHERS: "/api/users/teachers",
  COURSES: "/api/courses",
  GROUPS: "/api/groups",
  STUDENTS: "/api/students",
  USERS: "/api/users",
  COIN_TRANSACTIONS: "/api/coin-transactions",
  PURCHASES: "/api/purchases",
  MESSAGES: "/api/messages",
};
