export const ENDPOINTS = {
  REFRESH: "/api/auth/refresh",
  LOGIN: "/api/auth/login",
  ME: "/api/auth/me",
  LOGOUT: "/api/auth/logout",
  TENANTS: "/api/tenants",
  TEACHERS: "/api/users/teachers",
  TEACHER_SELF: "/api/teachers",
  COURSES: "/api/courses",
  GROUPS: "/api/groups",
  STUDENTS: "/api/students",
  USERS: "/api/users",
  STAFF: "/api/users/staff",
  ROLES: "/api/roles",
  COIN_TRANSACTIONS: "/api/coin-transactions",
  COIN_RULES: "/api/coin-rules",
  SESSIONS: "/api/sessions",
  REWARDS: "/api/rewards",
  REWARD_CATEGORIES: "/api/reward-category",
  PURCHASES: "/api/purchases",
  MESSAGES: "/api/messages",
  ROOMS: "/api/rooms",
  SUBJECTS: "/api/subjects",
  SCHEDULE_TEMPLATES: "/api/schedule-templates",
  SCHEDULE_EXCEPTIONS: "/api/schedule-exceptions",
};
